# Generated by Django 4.2.5 on 2023-09-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_quiz_question_lesson_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='is_multi',
        ),
    ]
