# Generated by Django 4.2.5 on 2023-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_type_question_is_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
